# Generated by Django 5.2.3 on 2025-06-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('duration', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_slow', models.BooleanField(default=False)),
                ('view_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url_path', models.CharField(blank=True, max_length=255, null=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_content_type', models.CharField(blank=True, help_text='Content-Type header of the request', max_length=100, null=True)),
                ('response_status_code', models.PositiveSmallIntegerField(help_text='HTTP status code of the response', null=True)),
            ],
            options={
                'verbose_name': 'Query Record',
                'verbose_name_plural': 'Query Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='query_optim_timesta_b9701c_idx'), models.Index(fields=['is_slow'], name='query_optim_is_slow_9e26c0_idx'), models.Index(fields=['duration'], name='query_optim_duratio_7bdf10_idx'), models.Index(fields=['view_name'], name='query_optim_view_na_4901f6_idx'), models.Index(fields=['is_slow', '-duration'], name='query_optim_is_slow_f2fc72_idx'), models.Index(fields=['view_name', '-timestamp'], name='query_optim_view_na_a0beb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.JSONField()),
                ('suggested_optimization', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('query_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='query_optimizer.queryrecord')),
            ],
            options={
                'verbose_name': 'Query Analysis',
                'verbose_name_plural': 'Query Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
